# 🚀 Day 9 — Data Cleaning

## AI/ML Engineer Bootcamp

Data Cleaning means finding and fixing problems in raw data.

Topics:
- Missing Values
- Duplicates
- Text Cleaning
- Data Types
- Filtering
- Sorting
- GroupBy
- Outliers

In [1]:
# Import Pandas 
import pandas as pd

# Import NumPy
import numpy as np

In [2]:
# Create a sample dataset 
data = {
    "Name": [" Gaurav", "Rahul ", "Priya", "Amit", "Gaurav"],
    "Age": [21, np.nan, 23, 25, 21],
    "Gender": ["M", "Male", "F", "Female", "M"],
    "Department": ["IT", "it", "HR", "Finance", "IT"],
    "Salary": [50000, 60000, np.nan, 55000, 50000]
}


df = pd.DataFrame(data)


df

      Name   Age  Gender Department   Salary
0   Gaurav  21.0       M         IT  50000.0
1   Rahul    NaN    Male         it  60000.0
2    Priya  23.0       F         HR      NaN
3     Amit  25.0  Female    Finance  55000.0
4   Gaurav  21.0       M         IT  50000.0

In [3]:
# Display the first 5 rows
print(df.head())

# Check number of rows and columns
print("\nShape:", df.shape)

      Name   Age  Gender Department   Salary
0   Gaurav  21.0       M         IT  50000.0
1   Rahul    NaN    Male         it  60000.0
2    Priya  23.0       F         HR      NaN
3     Amit  25.0  Female    Finance  55000.0
4   Gaurav  21.0       M         IT  50000.0

Shape: (5, 5)

In [7]:
print("\nColumns:", df.columns)
print("----------------------------------------------")

# Get information about columns, data types and missing value
df.info()

Columns: Index(['Name', 'Age', 'Gender', 'Department', 'Salary'], dtype='str')
----------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         4 non-null      float64
 2   Gender      5 non-null      str
 3   Department  5 non-null      str
 4   Salary      4 non-null      float64
dtypes: float64(2), str(3)
memory usage: 332.0 bytes

In [ ]:
# Get numerical statistics such as mean, min and max
print("\nStatistics:")
print(df.describe())

Statistics:
             Age        Salary
count   4.000000      4.000000
mean   22.500000  53750.000000
std     1.914854   4787.135539
min    21.000000  50000.000000
25%    21.000000  50000.000000
50%    22.000000  52500.000000
75%    23.500000  56250.000000
max    25.000000  60000.000000

In [8]:
# Check every cell for a missing value
print(df.isnull())

# Count missing values in each column
print("\nMissing Values:")
print(df.isnull().sum())

    Name    Age  Gender  Department  Salary
0  False  False   False       False   False
1  False   True   False       False   False
2  False  False   False       False    True
3  False  False   False       False   False
4  False  False   False       False   False

Missing Values:
Name          0
Age           1
Gender        0
Department    0
Salary        1
dtype: int64

In [9]:
# Fill missing Age values with the median Age
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Salary values with the median Salary
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

# Display cleaned data
df

      Name   Age  Gender Department   Salary
0   Gaurav  21.0       M         IT  50000.0
1   Rahul   22.0    Male         it  60000.0
2    Priya  23.0       F         HR  52500.0
3     Amit  25.0  Female    Finance  55000.0
4   Gaurav  21.0       M         IT  50000.0

In [10]:
# Count duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Display the result
df

Duplicate rows: 0

      Name   Age  Gender Department   Salary
0   Gaurav  21.0       M         IT  50000.0
1   Rahul   22.0    Male         it  60000.0
2    Priya  23.0       F         HR  52500.0
3     Amit  25.0  Female    Finance  55000.0
4   Gaurav  21.0       M         IT  50000.0

In [11]:
# Remove spaces before and after names
df["Name"] = df["Name"].str.strip()

In [12]:
df

     Name   Age  Gender Department   Salary
0  Gaurav  21.0       M         IT  50000.0
1   Rahul  22.0    Male         it  60000.0
2   Priya  23.0       F         HR  52500.0
3    Amit  25.0  Female    Finance  55000.0
4  Gaurav  21.0       M         IT  50000.0

In [14]:
# Convert M/F into full gender names
df["Gender"] = df["Gender"].replace({
    "M": "Male",
    "F": "Female"
})
df

     Name   Age  Gender Department   Salary
0  Gaurav  21.0    Male         IT  50000.0
1   Rahul  22.0    Male         it  60000.0
2   Priya  23.0  Female         HR  52500.0
3    Amit  25.0  Female    Finance  55000.0
4  Gaurav  21.0    Male         IT  50000.0

In [15]:
# Show unique gender values
print("Gender:")
print(df["Gender"].unique())

Gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [16]:
# Show unique department values
print("\nDepartment:")
print(df["Department"].unique())

Department:
<StringArray>
['IT', 'it', 'HR', 'Finance']
Length: 4, dtype: str

In [17]:
# Count each gender
print("\nGender Counts:")
print(df["Gender"].value_counts())

Gender Counts:
Gender
Male      3
Female    2
Name: count, dtype: int64

In [18]:
# Convert salary from rupees to lakhs
df["Salary_Lakh"] = df["Salary"] / 100000

# Display the DataFrame
df

     Name   Age  Gender Department   Salary  Salary_Lakh
0  Gaurav  21.0    Male         IT  50000.0        0.500
1   Rahul  22.0    Male         it  60000.0        0.600
2   Priya  23.0  Female         HR  52500.0        0.525
3    Amit  25.0  Female    Finance  55000.0        0.550
4  Gaurav  21.0    Male         IT  50000.0        0.500

In [19]:
# Select employees whose salary is greater than 50,000
high_salary = df[df["Salary"] > 50000]

high_salary

    Name   Age  Gender Department   Salary  Salary_Lakh
1  Rahul  22.0    Male         it  60000.0        0.600
2  Priya  23.0  Female         HR  52500.0        0.525
3   Amit  25.0  Female    Finance  55000.0        0.550

In [20]:
# Sort employees from highest to lowest salary
df.sort_values("Salary", ascending=False)

     Name   Age  Gender Department   Salary  Salary_Lakh
1   Rahul  22.0    Male         it  60000.0        0.600
3    Amit  25.0  Female    Finance  55000.0        0.550
2   Priya  23.0  Female         HR  52500.0        0.525
0  Gaurav  21.0    Male         IT  50000.0        0.500
4  Gaurav  21.0    Male         IT  50000.0        0.500

In [21]:
# Find the first quartile
Q1 = df["Salary"].quantile(0.25)

# Find the third quartile
Q3 = df["Salary"].quantile(0.75)

# Calculate the Interquartile Range
IQR = Q3 - Q1

# Calculate acceptable lower and upper limits
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

Lower Bound: 42500.0
Upper Bound: 62500.0

In [22]:
# Group employees by department
# Then calculate the average salary
df.groupby("Department")["Salary"].mean()

Department
Finance    55000.0
HR         52500.0
IT         50000.0
it         60000.0
Name: Salary, dtype: float64

In [23]:
# Check number of rows and columns
print("Shape:", df.shape)

# Check remaining missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Check remaining duplicates
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# Check data types
print("\nData Types:")
print(df.dtypes)

# Display final cleaned dataset
display(df)

Shape: (5, 6)

Missing Values:
Name           0
Age            0
Gender         0
Department     0
Salary         0
Salary_Lakh    0
dtype: int64

Duplicate Rows:
1

Data Types:
Name               str
Age            float64
Gender             str
Department         str
Salary         float64
Salary_Lakh    float64
dtype: object

     Name   Age  Gender Department   Salary  Salary_Lakh
0  Gaurav  21.0    Male         IT  50000.0        0.500
1   Rahul  22.0    Male         it  60000.0        0.600
2   Priya  23.0  Female         HR  52500.0        0.525
3    Amit  25.0  Female    Finance  55000.0        0.550
4  Gaurav  21.0    Male         IT  50000.0        0.500