In [1]:
# TOPIC: IMPORT LIBRARIES

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# TOPIC: DATA COLLECTION

data = {
    "Size": [500, 800, 1000, 1200, 1500, 1800, 2000, 2200, 2500, 2800],
    "Bedrooms": [1, 2, 2, 2, 3, 3, 4, 4, 4, 5],
    "Age": [15, 10, 8, 7, 5, 4, 3, 5, 2, 1],
    "Price": [15, 25, 32, 38, 48, 58, 65, 70, 82, 92]
}

df = pd.DataFrame(data)

df.head()

   Size  Bedrooms  Age  Price
0   500         1   15     15
1   800         2   10     25
2  1000         2    8     32
3  1200         2    7     38
4  1500         3    5     48

In [3]:
# TOPIC: DATA UNDERSTANDING

print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df.describe())

(10, 4)
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Size      10 non-null     int64
 1   Bedrooms  10 non-null     int64
 2   Age       10 non-null     int64
 3   Price     10 non-null     int64
dtypes: int64(4)
memory usage: 452.0 bytes
None
Size        0
Bedrooms    0
Age         0
Price       0
dtype: int64
              Size   Bedrooms        Age      Price
count    10.000000  10.000000  10.000000  10.000000
mean   1630.000000   3.000000   6.000000  52.500000
std     758.727004   1.247219   4.189935  25.246562
min     500.000000   1.000000   1.000000  15.000000
25%    1050.000000   2.000000   3.250000  33.500000
50%    1650.000000   3.000000   5.000000  53.000000
75%    2150.000000   4.000000   7.750000  68.750000
max    2800.000000   5.000000  15.000000  92.000000

In [4]:
# TOPIC: FEATURES (X) AND TARGET (y)

X = df[["Size", "Bedrooms", "Age"]]
y = df["Price"]

print("Features:")
display(X.head())

print("Target:")
display(y.head())

Features:

   Size  Bedrooms  Age
0   500         1   15
1   800         2   10
2  1000         2    8
3  1200         2    7
4  1500         3    5

Target:

0    15
1    25
2    32
3    38
4    48
Name: Price, dtype: int64

In [5]:
# TOPIC: TRAIN / TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 8
Testing rows: 2

In [6]:
# TOPIC: MODEL TRAINING

model = LinearRegression()

model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [7]:
# TOPIC: MODEL PREDICTION

y_pred = model.predict(X_test)

results = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_pred
})

display(results.round(2))

   Actual Price  Predicted Price
8            82            81.02
1            25            25.08

In [8]:
# TOPIC: MODEL EVALUATION

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R²:", round(r2, 3))

MAE: 0.53
RMSE: 0.69
R²: 0.999

In [9]:
# TOPIC: PREDICTION ON NEW DATA

new_house = pd.DataFrame({
    "Size": [1200],
    "Bedrooms": [3],
    "Age": [5]
})

predicted_price = model.predict(new_house)

print(f"Predicted house price: ₹{predicted_price[0]:.2f} lakh")

Predicted house price: ₹38.69 lakh