In [1]:
# Import Pandas
import pandas as pd

# Create a sample dataset
df = pd.DataFrame({
    "Age": [22, 25, 30, 35],
    "Income": [30000, 40000, 55000, 70000],
    "Bedrooms": [1, 2, 3, 4],
    "Price": [30, 45, 65, 90]
})

# Select only the input features
X = df[["Age", "Income", "Bedrooms"]]

# Display the features
X

   Age  Income  Bedrooms
0   22   30000         1
1   25   40000         2
2   30   55000         3
3   35   70000         4

In [2]:
# Select numerical features
numerical_features = df[["Age", "Income", "Bedrooms"]]

# Display numerical features
print(numerical_features)

   Age  Income  Bedrooms
0   22   30000         1
1   25   40000         2
2   30   55000         3
3   35   70000         4

In [3]:
# Add a categorical feature
df["City"] = ["Nashik", "Pune", "Mumbai", "Nashik"]

# Display the categorical feature
print(df["City"])

0    Nashik
1      Pune
2    Mumbai
3    Nashik
Name: City, dtype: str

In [4]:
# Create a new feature from existing features
df["Income_per_Age"] = df["Income"] / df["Age"]

# Display the newly created feature
print(df[["Income", "Age", "Income_per_Age"]])

   Income  Age  Income_per_Age
0   30000   22     1363.636364
1   40000   25     1600.000000
2   55000   30     1833.333333
3   70000   35     2000.000000

In [5]:
# Select only the features we want to use
selected_features = df[["Age", "Income", "Bedrooms"]]

# Display selected features
selected_features

   Age  Income  Bedrooms
0   22   30000         1
1   25   40000         2
2   30   55000         3
3   35   70000         4